# Generated by Django 6.0.3 on 2026-03-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_galleryimage_image_alter_galleryimage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('button_link', models.CharField(default='/about', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback URL', max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
