# Generated by Django 6.0.3 on 2026-03-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('hero_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('patron_title', models.CharField(default='St. Thomas, The Apostle', max_length=200)),
                ('patron_description_1', models.TextField(blank=True)),
                ('patron_description_2', models.TextField(blank=True)),
                ('patron_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('patron_image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': '📖 About Page Content',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_text', models.CharField(help_text="Display date e.g. 'March 28'", max_length=50)),
                ('tag', models.CharField(help_text='e.g. Liturgy, Youth, Event', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': '📢 Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Tivim, Bardez, Goa - 403502', max_length=300)),
                ('phone', models.CharField(default='+91 832 226 xxxx', max_length=50)),
                ('email', models.EmailField(default='stthomas.tivim@example.com', max_length=254)),
                ('office_hours', models.CharField(default='Mon–Sat, 9 AM – 5 PM', max_length=100)),
                ('google_maps_embed', models.URLField(blank=True, help_text='Google Maps embed URL', max_length=1000)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': '📞 Contact Info',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': '📧 Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MassTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(help_text='e.g. Monday – Friday, Sunday', max_length=50)),
                ('time', models.CharField(help_text='e.g. 6:30 AM', max_length=20)),
                ('label', models.CharField(help_text='e.g. Daily Mass, Vigil Mass', max_length=100)),
                ('language', models.CharField(default='English', help_text='e.g. English / Konkani', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mass Timing',
                'verbose_name_plural': '⏰ Mass Timings',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': '👥 Team Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g. 1581, Today', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': '📅 Timeline Events',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priest_name', models.CharField(default="Fr. John D'Souza", max_length=100)),
                ('priest_title', models.CharField(default='Parish Priest', max_length=100)),
                ('priest_image', models.ImageField(blank=True, null=True, upload_to='priest/')),
                ('priest_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('heading', models.CharField(default='A Warm Welcome', max_length=200)),
                ('quote_text', models.TextField(help_text='The main highlighted quote')),
                ('body_text', models.TextField(help_text='Additional paragraph text below the quote')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Welcome Message',
                'verbose_name_plural': '💬 Welcome Message',
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': '📝 Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': '🖼️ Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Hero Slide', 'verbose_name_plural': '🖼️ Hero Slides'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notice', 'verbose_name_plural': '📋 Notices'},
        ),
        migrations.AlterModelOptions(
            name='prayerrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prayer Request', 'verbose_name_plural': '🙏 Prayer Requests'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (fallback)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (fallback)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
    ]
