# Generated by Django 6.0.3 on 2026-03-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aboutpage_announcement_contactinfo_contactmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='St. Thomas Church', max_length=100)),
                ('site_tagline', models.CharField(default='Tivim, Goa', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo_url', models.URLField(blank=True, help_text='External logo URL (fallback)', max_length=500, null=True)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': '⚙️ Site Settings',
            },
        ),
    ]
