# Generated by Django 6.0.3 on 2026-03-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Feasts', 'Feasts'), ('Liturgy', 'Liturgy'), ('Architecture', 'Architecture'), ('Music', 'Music'), ('Youth', 'Youth'), ('Sacraments', 'Sacraments')], default='General', max_length=50),
        ),
    ]
