# Generated by Django 6.0.3 on 2026-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gallerycategory_alter_galleryimage_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page Content', 'verbose_name_plural': 'About Page Content'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Info'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Gallery Category', 'verbose_name_plural': 'Gallery Categories'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Hero Slide', 'verbose_name_plural': 'Hero Slides'},
        ),
        migrations.AlterModelOptions(
            name='masstiming',
            options={'ordering': ['order'], 'verbose_name': 'Mass Timing', 'verbose_name_plural': 'Mass Timings'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
        migrations.AlterModelOptions(
            name='prayerrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prayer Request', 'verbose_name_plural': 'Prayer Requests'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['order'], 'verbose_name': 'Timeline Event', 'verbose_name_plural': 'Timeline Events'},
        ),
        migrations.AlterModelOptions(
            name='welcomemessage',
            options={'verbose_name': 'Welcome Message', 'verbose_name_plural': 'Welcome Message'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
