# Generated by Django 6.0.3 on 2026-04-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_aboutpage_options_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_text',
            field=models.CharField(default='St. Thomas Church, Tivim, Goa. All rights reserved.', help_text='Custom copyright text (e.g. Church Name, Address)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_mission_statement',
            field=models.TextField(default='Serving the faithful of Tivim, Goa. A beacon of faith, hope, and community in the heart of our village.', help_text='The short description that appears under the logo in the footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_privacy_policy_url',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_terms_url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
