# Generated by Django 6.0.3 on 2026-04-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sitesettings_footer_copyright_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='google_maps_embed',
            field=models.TextField(blank=True, help_text='Paste the full Google Maps <iframe> code here'),
        ),
    ]
