# Generated by Django 6.0.3 on 2026-04-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_contactinfo_google_maps_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='header_image_url',
            field=models.URLField(blank=True, help_text='External image URL (fallback)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='page_title',
            field=models.CharField(default='Contact Us', max_length=100),
        ),
    ]
