# Generated by Django 6.0.3 on 2026-04-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_contactinfo_header_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='Contact Us', max_length=150)),
                ('header_background_image', models.ImageField(blank=True, null=True, upload_to='contact_page/')),
                ('header_image_external_url', models.URLField(blank=True, help_text='Paste a link if not uploading an image', max_length=500, null=True)),
                ('physical_address', models.TextField(default='Tivim, Bardez, Goa - 403502')),
                ('contact_phone_number', models.CharField(default='+91 832 226 xxxx', max_length=100)),
                ('contact_email_address', models.EmailField(default='stthomas.tivim@example.com', max_length=254)),
                ('office_operating_hours', models.CharField(default='Mon–Sat, 9 AM – 5 PM', max_length=150)),
                ('google_maps_iframe_code', models.TextField(blank=True, help_text='Paste the Share -> Embed code from Google Maps here')),
            ],
            options={
                'verbose_name': 'Contact Page Configuration',
                'verbose_name_plural': 'Contact Page Configuration',
            },
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
