# Generated by Django 6.0.3 on 2026-04-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_contactpagesettings_delete_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_text', models.TextField(help_text='The scripture text')),
                ('reference', models.CharField(help_text='e.g. John 3:16', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Bible Verse',
                'verbose_name_plural': 'Daily Bible Verses',
                'ordering': ['-created_at'],
            },
        ),
    ]
