"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-^&g^q7yci53*0i+tf7=ho7%tkm@37tdfmg$i%&6-kstd=ul2u8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,.vercel.app', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / '../frontend/dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / '../frontend/dist',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# CORS configuration
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:3000,http://localhost:5173', cast=Csv())

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_SECURITY_POLICY = {
        'default-src': ('\'self\'',),
        'script-src': ('\'self\'', '\'unsafe-inline\''),
        'style-src': ('\'self\'', '\'unsafe-inline\''),
        'img-src': ('\'self\'', 'data:', 'https:'),
        'font-src': ('\'self\'',),
    }

    # Trust Vercel's proxy for HTTPS detection
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO' if not DEBUG else 'DEBUG',
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── JAZZMIN ADMIN THEME ──────────────────────────────────────
JAZZMIN_SETTINGS = {
    'site_title': 'St. Thomas CMS',
    'site_header': 'St. Thomas Church',
    'site_brand': 'St. Thomas CMS',
    'welcome_sign': 'Welcome to St. Thomas Church CMS',
    'copyright': 'St. Thomas Catholic Church, Tivim, Goa',

    # Search bar
    'search_model': ['api.BlogPost', 'api.GalleryImage'],

    # Top menu links
    'topmenu_links': [
        {'name': 'View Website', 'url': '/', 'new_window': True},
        {'name': 'API', 'url': '/api/', 'new_window': True},
    ],

    # Show the sidebar (True) or a horizontal nav (False)
    'show_sidebar': True,
    'navigation_expanded': True,

    # Organize models into groups in sidebar
    'order_with_respect_to': [
        'api.HeroSlide',
        'api.MassTiming',
        'api.WelcomeMessage',
        'api.Announcement',
        'api.TimelineEvent',
        'api.TeamMember',
        'api.AboutPage',
        'api.GalleryCategory',
        'api.GalleryImage',
        'api.BlogPost',

        'api.ContactInfo',
        'api.ContactMessage',
        'api.Notice',
        'api.PrayerRequest',
        'api.SiteSettings',
    ],


    # Icons for sidebar
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'api.HeroSlide': 'fas fa-images',
        'api.MassTiming': 'fas fa-clock',
        'api.WelcomeMessage': 'fas fa-comment-dots',
        'api.Announcement': 'fas fa-bullhorn',
        'api.TimelineEvent': 'fas fa-calendar-alt',
        'api.TeamMember': 'fas fa-user-tie',
        'api.AboutPage': 'fas fa-book-open',
        'api.GalleryCategory': 'fas fa-folder-open',
        'api.GalleryImage': 'fas fa-camera',

        'api.BlogPost': 'fas fa-pen-fancy',
        'api.ContactInfo': 'fas fa-map-marker-alt',
        'api.ContactMessage': 'fas fa-envelope',
        'api.Notice': 'fas fa-clipboard-list',
        'api.PrayerRequest': 'fas fa-praying-hands',
        'api.SiteSettings': 'fas fa-cogs',
    },


    'default_icon_parents': 'fas fa-folder',
    'default_icon_children': 'fas fa-circle',

    'show_ui_builder': False,
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': 'navbar-light',
    'accent': 'accent-info',
    'navbar': 'navbar-light navbar-white',
    'no_navbar_border': True,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-light-primary',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': False,
    'theme': 'flatly',
    'dark_mode_theme': None,
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success'
    }
}
